### ISSUE TITLE
@nestjs/platform-fastify bug

### ISSUE THREAD

**Issue by Tam2** [s-r-x/bull-monitor#49]
I've tried to set this up with my nestjs queue consumer but i keep getting the following error: when trying to use `BullMonitorFastify`

```
[Nest] 30444  - 10/02/2022, 17:09:20   ERROR [ExceptionsHandler] this.willStart is not a function
TypeError: this.willStart is not a function
    at ApolloServer.createHandler (C:\x\node_modules\apollo-server-fastify\src\ApolloServer.ts:44:35)
    at plugin (C:\x\node_modules\@bull-monitor\fastify\src\index.ts:12:21)
    at Object.use (C:\x\node_modules\@nestjs\core\middleware\utils.js:51:24)
    at C:\x\node_modules\@nestjs\core\router\router-proxy.js:9:23
    at Holder.done (C:\x\node_modules\middie\engine.js:107:13)
    at Object.run (C:\x\node_modules\middie\engine.js:59:12)
    at Object.runMiddie (C:\x\node_modules\middie\index.js:41:21)
    at hookIterator (C:\x\node_modules\fastify\lib\hooks.js:237:10)
    at next (C:\x\node_modules\fastify\lib\hooks.js:164:16)
    at hookRunner (C:\x\node_modules\fastify\lib\hooks.js:187:3)

```
bull-monitor.service.ts
```
import { BullMonitorFastify } from '@bull-monitor/fastify';
import { InjectQueue } from '@nestjs/bull';
import { Injectable } from '@nestjs/common';
import { Queue } from 'bull';
import { BullAdapter } from '@bull-monitor/root/dist/bull-adapter';
import { QueueName } from '@composer/queue/enums/index.enum';

@Injectable()
export class BullMonitorService extends BullMonitorFastify {
  constructor(
    @InjectQueue(QueueName.FEED) feedQueue: Queue,
    @InjectQueue(QueueName.STOCK) stockQueue: Queue
  ) {
    super({
      queues: [new BullAdapter(feedQueue), new BullAdapter(stockQueue)],
    });
  }
}
```

My QueueServiceModule (aka AppModule)

```
import { MiddlewareConsumer, Module } from '@nestjs/common';
import { BullModule } from '@nestjs/bull';
import { QueueName } from '@composer/queue/enums/queues.enum';
import { StockConsumer } from './consumers/stock.consumer';
import { FeedConsumer } from './consumers/feed.consumer';
import { HttpModule } from '@nestjs/axios';
import { StockModule } from '@composer/stock';
import { ClientModule } from '@composer/client';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ConfigService, ConfigModule } from '@nestjs/config';
import { CoreModule } from '@composer/core';
import { IntegrationsModule } from '@composer/integrations';
import configuration from '@composer/core/config/configuration';
import { BullMonitorService } from './bull-monitor.service';

@Module({
  imports: [
    CoreModule,
    ConfigModule.forRoot({
      load: [configuration],
    }),
    BullModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        redis: {
          port: parseInt(configService.get('bullMq.redis.port')),
          host: configService.get('bullMq.redis.host'),
          password: configService.get('bullMq.redis.password'),
          tls: {
            servername: configService.get('bullMq.redis.host'),
          },
        },
        defaultJobOptions: configService.get('bullMq.defaultJobOptions'),
      }),
      inject: [ConfigService],
    }),
    BullModule.registerQueue(
      {
        name: QueueName.STOCK,
      },
      {
        name: QueueName.FEED,
      }
    ),
    HttpModule,
    TypeOrmModule.forRootAsync({
      imports: [ConfigModule],
      useFactory: async (configService: ConfigService) => ({
        type: 'mssql',
        host: configService.get('database.host'),
        port: parseInt(configService.get('database.port')),
        username: configService.get('database.username'),
        password: configService.get('database.password'),
        options: {
          enableArithAbort: true,
          trustServerCertificate: true,
        },
        pool: {
          min: 0,
          max: 100,
        },
        maxQueryExecutionTime: 500,
        logger: 'advanced-console',
        autoLoadEntities: true,
      }),
      inject: [ConfigService],
    }),
    IntegrationsModule,
    StockModule,
    ClientModule,
  ],
  providers: [StockConsumer, FeedConsumer, BullMonitorService],
})
export class QueueServiceModule {
  constructor(private monitor: BullMonitorService) {}
  async configure(consumer: MiddlewareConsumer) {
    await this.monitor.init();
    consumer.apply(this.monitor.plugin).forRoutes('/bull-monitor');
  }
}
```

**Comment by s-r-x** [comment]
@Tam2 hello. Looks like a fastify version conflict, but i'm not sure. We are using an alpha version of apollo server fastify which only works with fastify 3.x. Maybe you are using fastify 2.x?

**Comment by Tam2** [comment]
I'm using @nestjs/platform-fastify 8.2.6 which looks like it's using "fastify": "3.27.1", - https://github.com/nestjs/nest/blob/master/packages/platform-fastify/package.json

Sample of my main.ts

```
import {
  FastifyAdapter,
  NestFastifyApplication,
} from '@nestjs/platform-fastify';

async function bootstrap() {
  const app = await NestFactory.create<NestFastifyApplication>(
    QueueServiceModule,
    new FastifyAdapter()
  );
  await app.listen(3001, '0.0.0.0');
}
bootstrap();
```

**Comment by s-r-x** [comment]
@Tam2, that's weird. Unfortunately i don't have enough time to debug this one atm. So in case you'll able to resolve this issue by yourself - please leave the solution here for future folks 🙏

**Comment by s-r-x** [comment]
@Tam2 check out the version 4.0.0. the only problem is that you need to access the fastify instance somehow, when calling monitor.init(), but something like this should work:

```typescript
import { Module, NestModule, Injectable } from '@nestjs/common';
import { HttpAdapterHost } from '@nestjs/core';
import { FastifyAdapter } from '@nestjs/platform-fastify';
import { BullMonitorFastify } from '@bull-monitor/fastify';

@Injectable()
export class BullMonitorService extends BullMonitorFastify {
  constructor() {
    super({ queues: [], baseUrl: '/my/url' });
  }
}

@Module({ providers: [BullMonitorService] })
export class BullMonitorModule implements NestModule {
  constructor(
    private adapterHost: HttpAdapterHost<FastifyAdapter>,
    private monitor: BullMonitorService,
  ) {}
  async configure() {
    const instance = this.adapterHost.httpAdapter.getInstance();
    await this.monitor.init({ app: instance });
    await instance.register(this.monitor.plugin);
  }
}
```
