### ISSUE TITLE
GraphQLError: Enum "JobStatus" cannot represent value: "unknown"

### ISSUE THREAD

**Issue by autarchprinceps** [s-r-x/bull-monitor#67]
According to https://api.docs.bullmq.io/classes/Job.html#getState unknown is an expectable value for a job state, but bull monitor fails with the following and completely crashes the UI entirely.
```
GraphQLError: Enum "JobStatus" cannot represent value: "unknown"                                                                           
    at GraphQLEnumType.serialize (/usr/local/lib/node_modules/@bull-monitor/cli/node_modules/graphql/type/definition.js:1103:13)           
    at completeLeafValue (/usr/local/lib/node_modules/@bull-monitor/cli/node_modules/graphql/execution/execute.js:738:39)                  
    at completeValue (/usr/local/lib/node_modules/@bull-monitor/cli/node_modules/graphql/execution/execute.js:619:12)                      
    at completeValue (/usr/local/lib/node_modules/@bull-monitor/cli/node_modules/graphql/execution/execute.js:584:23)                      
    at /usr/local/lib/node_modules/@bull-monitor/cli/node_modules/graphql/execution/execute.js:486:9                                       
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                          
    at async Promise.all (index 4) {                                                                                                       
  path: [ 'jobs', 0, 'status' ],                                                                                                           
  locations: [ { line: 8, column: 5 } ],                                                                                                   
  extensions: [Object: null prototype] {}                                                                                                  
}   
```

**Comment by s-r-x** [comment]
fixed in **5.0.2**
